#!/bin/bash
# vim: ft=sh


#! /bin/sh

#https://github.com/goubew/dotfiles/blob/0d2bd6283c132b63dda17eb2f6063180db662796/bspwmrc
color_lookup () {
  # arg: xrdb color name
  xrdb -query | grep -E "^\*$1\:" | head -n 1 | awk '{print $2}'
}

# => I-Term II-Web III-Editor IV-File V-Music VI-Irc VII-Other VIII-Email IX X
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

#bspc config top_padding          2
bspc config split_ratio          0.52

bspc config active_border_color  $(color_lookup 'foreground')
bspc config normal_border_color  $(color_lookup 'background')
bspc config focused_border_color $(color_lookup 'foreground')

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc rule -a rofi state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a seafile-applet desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a Firefox floating=off desktop=^2
bspc rule -a Chromium floating=off desktop=^2
bspc rule -a URxvt:main desktop=^1
bspc rule -a URxvt:ranger floating=off desktop=^4
bspc rule -a URxvt:ncmpcpp floating=off desktop=^5
bspc rule -a URxvt:alsamixer floating=off desktop=^5
bspc rule -a URxvt:newsbeuter floating=off desktop=^6
bspc rule -a URxvt:rtorrent desktop=^9
bspc rule -a URxvt:cprogram desktop=^4
bspc rule -a URxvt:mutt desktop=^6
bspc rule -a URxvt:vim desktop=^3
bspc rule -a Zathura floating=off desktop=^4
bspc rule -a Thunar floating=off desktop=^4
bspc rule -a sun-awt-X11-XDialogPeer state=floating



setxkbmap -layout de

/home/fkheinstein/.config/bspwm/start.sh "compton --config  /home/fkheinstein/.compton.conf"

compton &
sleep 2

/home/fkheinstein/.config/bspwm/start.sh "feh --randomize --bg-fill /home/fkheinstein/.wallpapers"

/home/fkheinstein/.config/bspwm/start.sh "seafile-applet "
/home/fkheinstein/.config/bspwm/start.sh "mpd /home/fkheinstein/.mpd/mpd.conf "
/home/fkheinstein/.config/bspwm/start.sh "dropbox "
/home/fkheinstein/.config/bspwm/start.sh "sxhkd "


/home/fkheinstein/.config/polybar/launch.sh &

urxvt -name main        -title main &
urxvt -name ncmpcpp     -title ncmpcpp -e ncmpcpp &
urxvt -name ncmpcpp                    -e ncmpcpp -s visualizer &
urxvt -name ncmpcpp                    -e ncmpcpp -s browser &
urxvt -name Tmux-Ranger                -e tmux new "ranger"  &

#urxvt -name Tmux -e bash -c "tmux"

#urxvt -name newsbeuter                 -e newsbeuter  &
#urxvt -name vim-Todo -T vim -e tmux new "vim ~/ToDoText"
#urxvt -name LURxvt -ls -e bash -c "[ -z "$TMUX"  ] && { tmux attach || tmux new-session;}"
