#. $XDG_CONFIG_HOME/colors/bash.current

# COLOR_DEFAULT_FG="#a7a5a5"
# COLOR_DEFAULT_BG="#333232"
# COLOR_MONITOR_FG="#8dbcdf"
# COLOR_MONITOR_BG="#333232"
# COLOR_FOCUSED_MONITOR_FG="#b1d0e8"
# COLOR_FOCUSED_MONITOR_BG="#144b6c"
# COLOR_FREE_FG="#737171"
# COLOR_FREE_BG="#333232"
# COLOR_FOCUSED_FREE_FG="#000000"
# COLOR_FOCUSED_FREE_BG="#504e4e"
# COLOR_OCCUPIED_FG="#a7a5a5"
# COLOR_OCCUPIED_BG="#333232"
# COLOR_FOCUSED_OCCUPIED_FG="#d6d3d2"
# COLOR_FOCUSED_OCCUPIED_BG="#504e4e"
# COLOR_URGENT_FG="#f15d66"
# COLOR_URGENT_BG="#333232"
# COLOR_FOCUSED_URGENT_FG="#501d1f"
# COLOR_FOCUSED_URGENT_BG="#d5443e"
# COLOR_STATE_FG="#89b09c"
# COLOR_STATE_BG="#333232"
# COLOR_TITLE_FG="#a8a2c0"
# COLOR_TITLE_BG="#333232"
# COLOR_SYS_FG="#b1a57d"
# COLOR_SYS_BG="#333232"

# Ivorylight by baskerville
# special
COLORFG='#6D727E'
COLORBG='#FEF9EC'
COLORCC='#6D727E'

# black
COLOR00='#C5C1B4'
COLOR08='#A1A6B2'

# red
COLOR01='#E75C58'
COLOR09='#B22B31'

# green
COLOR02='#00A250'
COLOR10='#007427'

# yellow
COLOR03='#A08A00'
COLOR11='#715F00'

# blue
COLOR04='#208FFB'
COLOR12='#0065CA'

# magenta
COLOR05='#D160C4'
COLOR13='#A03196'

# cyan
COLOR06='#00A4C1'
COLOR14='#007693'

# white
COLOR07='#3E424D'
COLOR15='#282C36'



COLOR_DEFAULT_FG=$COLORFG
COLOR_DEFAULT_BG=$COLORBG
COLOR_MONITOR_FG=$COLORFG
COLOR_MONITOR_BG=$COLORBG
COLOR_FOCUSED_MONITOR_FG=$COLORBG
COLOR_FOCUSED_MONITOR_BG=$COLORFG
COLOR_FREE_FG=$COLORFG
COLOR_FREE_BG=$COLORBG
COLOR_FOCUSED_FREE_FG=$COLORBG
COLOR_FOCUSED_FREE_BG=$COLORFG
COLOR_OCCUPIED_FG=$COLORFG
COLOR_OCCUPIED_BG=$COLORBG
COLOR_FOCUSED_OCCUPIED_FG=$COLORBG
COLOR_FOCUSED_OCCUPIED_BG=$COLORFG
COLOR_URGENT_FG=$COLORFG
COLOR_URGENT_BG=$COLORBG
COLOR_FOCUSED_URGENT_FG=$COLORBG
COLOR_FOCUSED_URGENT_BG=$COLORFG
COLOR_STATE_FG=$COLORBG
COLOR_STATE_BG=$COLOR00
COLOR_TITLE_FG=$COLORFG
COLOR_TITLE_BG=$COLORBG
COLOR_SYS_FG=$COLORFG
COLOR_SYS_BG=$COLORBG



## Colors
#alpha="#"
#
#xolor(){
#  echo -n "$( xrdb -query | grep "\*$1:" | grep -oE "#[a-zA-Z0-9]{6}" | cut -c 2- )";
#}
#
#COLORBG='$alpha$(xolor background)'
#COLORFG='$alpha$(xolor foreground)'
#COLOR00='$alpha$(xolor color0)'
#COLOR01='$alpha$(xolor color1)'
#COLOR02='$alpha$(xolor color2)'
#COLOR03='$alpha$(xolor color3)'
#COLOR04='$alpha$(xolor color4)'
#COLOR05='$alpha$(xolor color5)'
#COLOR06='$alpha$(xolor color6)'
#COLOR07='$alpha$(xolor color6)'
#COLOR08='$alpha$(xolor color8)'
#COLOR09='$alpha$(xolor color9)'
#COLOR10='$alpha$(xolor color10)'
#COLOR11='$alpha$(xolor color11)'
#COLOR12='$alpha$(xolor color12)'
#COLOR13='$alpha$(xolor color13)'
#COLOR14='$alpha$(xolor color14)'
#COLOR15='$alpha$(xolor color15)'



COLOR_DEFAULT_FG=$COLORFG
COLOR_DEFAULT_BG=$COLORBG
COLOR_MONITOR_FG=$COLORFG
COLOR_MONITOR_BG=$COLORBG
COLOR_FOCUSED_MONITOR_FG=$COLORBG
COLOR_FOCUSED_MONITOR_BG=$COLORFG
COLOR_FREE_FG=$COLORFG
COLOR_FREE_BG=$COLORBG
COLOR_FOCUSED_FREE_FG=$COLORBG
COLOR_FOCUSED_FREE_BG=$COLORFG
COLOR_OCCUPIED_FG=$COLORFG
COLOR_OCCUPIED_BG=$COLORBG
COLOR_FOCUSED_OCCUPIED_FG=$COLORBG
COLOR_FOCUSED_OCCUPIED_BG=$COLORFG
COLOR_URGENT_FG=$COLORFG
COLOR_URGENT_BG=$COLORBG
COLOR_FOCUSED_URGENT_FG=$COLORBG
COLOR_FOCUSED_URGENT_BG=$COLORFG
COLOR_STATE_FG=$COLORBG
COLOR_STATE_BG=$COLOR00
COLOR_TITLE_FG=$COLORFG
COLOR_TITLE_BG=$COLORBG
COLOR_SYS_FG=$COLORFG
COLOR_SYS_BG=$COLORBG