#!/bin/bash
#           ██          ██
#          ░░          ░░
#   ██   ██ ██ ███████  ██ ██████  █████
#  ░░██ ██ ░██░░██░░░██░██░░██░░█ ██░░░██
#   ░░███  ░██ ░██  ░██░██ ░██ ░ ░██  ░░
#    ██░██ ░██ ░██  ░██░██ ░██   ░██   ██
#   ██ ░░██░██ ███  ░██░██░███   ░░█████
#  ░░   ░░ ░░ ░░░   ░░ ░░ ░░░     ░░░░░




# This deals with dbus, etc.
 if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?* ; do
      [ -x "$f" ] && . "$f"

   done
   unset f
 fi

 
if [ `type -P xbindkeys` ]; then
    # Load custom keyboard key bindings
    xbindkeys
fi;


# You’ll be using the gnome-keyring to save your wifi passwords and since you don’t want the rest of the GNOME desktop, 
# add this to your ~/.xinitrc file

# Start a D-Bus session
source /etc/X11/xinit/xinitrc.d/30-dbus


if dcheck /usr/bin/gnome-keyring-daemon; then
	# Start GNOME Keyring
	eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)

	# You probably need to do this too:
	export SSH_AUTH_SOCK
	export GPG_AGENT_INFO
	export GNOME_KEYRING_CONTROL
	export GNOME_KEYRING_PID
fi


#█▓▒░ add font paths
#xset +fp /usr/share/fonts/artwiz-latin1-fonts
xset +fp /usr/share/fonts
xset +fp ~/.fonts
xset +fp /usr/share/fonts/local
xset  fp rehash



#█▓▒░ keyboard distribution
setxkbmap de
setxkbmap -option terminate:ctrl_alt_bksp
xrandr --dpi  140


# Use slock as our lock
# use 600 seconds or 10 minutes
#sh $HOME/.bin/xsidle.sh slock 600 &
#sh $HOME/.bin/lock.sh &

# Set wallpaper
feh --randomize --bg-scale ~/.wallpapers/* &

# Start our conkies
#conky -c ~/.config/conky/inspirationalquote &
#conky -c ~/.config/conky/Filesystems &
#conky -c ~/.config/conky/SystemInfo &


#█▓▒░ personal
compton --config ~/.compton.conf -cGb &
#xsetroot -cursor_name left_ptr &



xrdb -merge .Xresources
xcompmgr &





#nm-applet &
#seafile-applet &
#udiskie &



# Start my terminals

#urxvt -e zsh &
#urxvt -e htop &

# Programs
#urxvt -name mutt -e mutt  &
#urxvt -name mocp -e mocp   &


#dunst &
#sxhkd &


# Set up an icon tray
#stalonetray &

## start window manager


##█▓▒░ select WM
#pulseaudio --start
#sxhkd &
#sxhkd -c '~/.config/sxhkd/sxhkdrc' &
#exec bspwm &>~/bspwm.log
#exec bspwm
#exec i3  &>~/i3.log
#exec awesome  &>~/awesome.log
#exec xmonad  &>~/xmonad.log
exec xfce4-session  &>~/xfce4-session.log



#pulseaudio --start
#exec dwm  &>~/dwm.log


# start herbstluftwm in locked mode (it will be unlocked at the end of your
# autostart)

#tint2
#
#exec start-pulseaudio-x11 &
#pulseaudio --start
#exec wm
#sxhkd -c $HOME/.config/sxhkd/herbstluftwm &
#exec herbstluftwm --locked
#exec herbstluftwm  --locked &>~/herbstluft.log

# start wm
session=${1:-cwm}

case $session in
  2bw) sxhkd &
       exec 2bwm ;;
  2wm) sxhkd -c ~/.config/sxhkd/sxhkdrc.2wm &
       exec 2wm ;;
  awe) sxhkd -c ~/.config/sxhkd/sxhkdrc.awe &
       exec awesome ;;
  bsp) exec bspwm ;;
  cwm) sxhkd &
       minibar &
       exec cwm ;;
  dwm) sxhkd -c ~/.config/sxhkd/sxhkdrc.dwm &
       exec dwm-start ;;
  hrb) sxhkd &
       exec herbstluftwm --locked ;;
  nil) sxhkd -c ~/.config/sxhkd/sxhkdrc.wmutils &
       minibar &
       wew | yawee &
       exec xwait ;;
  pek) sxhkd &
       exec pekwm ;;
  spc) sxhkd &
       exec spectrwm ;;
  swm) sxhkd -c ~/.config/sxhkd/sxhkdrc.swm &
       minibar &
       exec swm ;;
  wch) sxhkd -c ~/.config/sxhkd/sxhkdrc.windowchef &
       exec windowchef ;;
  xmo) sxhkd -c ~/.config/sxhkd/sxhkdrc.xmo &
       exec xmonad ;;
  *  ) exec $1 ;;
esac
