#!/usr/bin/env bash

#make a terminal layout on first screen
function hc() {
    herbstclient "$@"
}

Mod=Mod4

if ! hc tag_status | grep "terms" >/dev/null || [[ $1 = -f ]]  ; then
	TAGS=$(hc tag_status | wc -w)
	hc add "terms"
	if [[ $TAGS -ge 9 ]] ; then
		echo "$0: too many tags; will not get a keybinding" >&2
	else
		hc keybind "$Mod-$(( TAGS + 1 ))" use "terms"
		hc keybind "$Mod-Shift-$(( TAGS + 1 ))" move "terms"
	fi
fi

# layout
hc load terms '
(split horizontal:0.450000:1
  (split vertical:0.500000:0
    (split vertical:0.500000:1
	  (clients vertical:0 )
	  (clients vertical:0 ))
   	(clients horizontal:0 ))
  (split vertical:0.550000:0
    (clients vertical:0 )
   	(clients vertical:0 )))'
# rules
hc rule instance="newsbeuter" tag=terms index=000
hc rule instance="mutt" tag=terms index=001
hc rule instance="irssi" tag=terms index=10
hc rule instance="ncmpcpp" tag=terms index=01
hc rule instance="wyrd" tag=terms index=11



# autostart applications
pgrep newsbeuter >/dev/null || urxvt -name newsbeuter -e newsbeuter &
pgrep mutt >/dev/null || urxvt -name mutt -e mutt &
pgrep ncmpcpp >/dev/null || urxvt -name ncmpcpp -e ncmpcpp &
screen -ls | grep "irssi[[:space:]]*(Attached)" >/dev/null || urxvt -name irssi -e screen -S irssi -xR irssi &
pgrep wyrd >/dev/null || urxvt -name wyrd -e wyrd &