#!/usr/bin/env bash
# Keybindings for herbstluftwm



# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4      # Use alt as the main modifier
MySuper=Mod1    # Use the super key as the main modifier


hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r chain , spawn echo "!! HLWM reload config !!" , reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn $terminal
hc keybind Alt-Return spawn termite


#Application
#hc keybind $Mod-Control-m "termite --title mutt -e mutt"
#hc keybind $Mod-Control-r "termite --title ranger -e 'ranger  ~/Seafile/dotfiles/system'"
#hc keybind $Mod-Control-w "termite --title weather -e weather"
#hc keybind $Mod-Control-s "termite -title speedometer 'sudo speedometer -r wlp2s0 -t wlp2s0'"
#hc keybind $Mod-Control-c "termite --title weechat -e weechat"


hc keybind $Mod-bracketleft  spawn rofi-bibbrowser
hc keybind $Mod-apostrophe   spawn /home/fkheinstein/.bin/wmscripts/rofi-mpd.sh
hc keybind $Mod-backslash    spawn /home/fkheinstein/.bin/wmscripts/rofi-pass.sh

videodir=/mnt/unterhaltung/video/
[[ -d ~/video ]] && videodir=$HOME/Videos/
hc keybind $Mod-Shift-apostrophe spawn  /home/fkheinstein/.bin/wmscripts/rofi-file-open.sh "$videodir"


hc keybind $Mod-F1        spawn spawn  /home/fkheinstein/.bin/wmscripts/external-monitor.sh

#urxvtc -name music -e  sh -c 'ncmpcpp -s playlist -S visualizer' &

#hc keybind $MySuper-m      spawn urxvt -name mutt -e mutt
#hc keybind $MySuper-n       spawn mpd && urxvt -name ncmpcpp -e sh -c  'ncmpcpp -s visualizer -S clock'
#hc keybind $MySuper-w      spawn urxvt -name weather -e weather
#hc keybind $MySuper-Shift-s      spawn urxvt -name speedometer 'sudo speedometer -r wlp3s0 -t wlp3s0'
#hc keybind $MySuper-c      spawn urxvt -name weechat -e weechat

#hc keybind $MySuper-v      spawn urxvtc -name vim -e vim
#hc keybind $MySuper-r      spawn urxvtc -name ranger -e ranger
#hc keybind $MySuper-r      spawn urxvt -name ranger -e 'ranger  ~/Seafile/dotfiles/system'
#hc keybind $MySuper-s      spawn subl3
#hc keybind $MySuper-t      spawn telegram-desktop
#hc keybind $MySuper-h      spawn hexchat


# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.75
hc keybind $Mod-o       split   right   0.75
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left  +$resizestep
hc keybind $Mod-Control-j       resize down  +$resizestep
hc keybind $Mod-Control-k       resize up    +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep



# Media Key
hc keybind XF86AudioRaiseVolume spawn amixer -q set Master 5%+ unmute
hc keybind XF86AudioLowerVolume spawn amixer -q set Master 5%- unmute

hc keybind XF86MonBrightnessDown spawn xbacklight -dec 5
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 5

hc keybind XF86KbdBrightnessDown spawn  kbdlight down 5
hc keybind XF86KbdBrightnessUp spawn kbdlight up 5

hc keybind XF86AudioMute spawn  amixer -q set Master toggle
hc keybind XF86AudioLowerVolume spawn  amixer -q set Master 5%-
hc keybind XF86AudioRaiseVolume spawn  amixer -q set Master 5%+

hc keybind XF86AudioPrev spawn  mpc prev
hc keybind XF86AudioPlay spawn  mpc toggle
hc keybind XF86AudioNext spawn  mpc next
#hc keybind XF86AudioPrev spawn  dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
#hc keybind XF86AudioPlay spawn  dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
#hc keybind XF86AudioNext spawn  dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next

hc keybind XF86LaunchA spawn chromium
hc keybind XF86LaunchB spawn thunar

hc keybind $Mod-Shift-w spawn feh --bg-scale --randomize ${HOME}/.wallpapers/*



hc keybind $Mod-Shift-d spawn dmenu_run -i -p "Run:" -fn "-*-terminus-*-*-*-*-12-*-*-*-*-*-*-*" -nb ${color["black"]} -nf ${color["white"]} -sb ${color["white"]} -sf ${color["green"]}
hc keybind $Mod-d spawn dmenu_run -i -p "Run:" -fn "-*-terminus-*-*-*-*-12-*-*-*-*-*-*-*" -nb ${color["black"]} -nf ${color["white"]} -sb ${color["white"]} -sf ${color["green"]}

hc keybind $Mod-Shift-space spawn rofi -show run
hc keybind $Mod-Tab spawn rofi -show window
hc keybind $Mod-Shift-x spawn rofi -columns 3 -show run
hc keybind $Mod-x spawn rofi -columns 3 -shocdrun


hc keybind $Mod-Shift-p spawn scrot '%Y-%m-%d_$wx$h.png'  -e 'mkdir -p ~/Pictures/Screenshots; mv $f ~/Pictures/Screenshots/'
hc keybind Print spawn scrot '%Y-%m-%d_%H-%M-%S_$wx$h.png' -e 'mkdir -p ~/Pictures/Screenshots; mv $f ~/Pictures/Screenshots &amp; mirage ~/Pictures/Screenshots/$f' -q 100
hc keybind $Mod-Print spawn scrot '%Y-%m-%d_%H-%M-%S_$wx$h.png' -e 'mkdir -p ~/Pictures/Screenshots; mv $f ~/Pictures/Screenshots &amp; mirage ~/Pictures/Screenshots/$f' -q 100 -u -b


# Selecting workspaces
hc keybind Alt-Control-Left 	use_index -1  --skip-visible
hc keybind Alt-Control-Right 	use_index +1  --skip-visible
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible


# layouting
hc keybind $Mod-r remove

hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-v split vertical 0.5
hc keybind $Mod-Shift-v split horizontal 0.5
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle


# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
#hc mousebind $Mod-Button4 call substitute WID clients.dragged.winid spawn transset-df --inc -i WID 0.05
#hc mousebind $Mod-Button5 call substitute WID clients.dragged.winid spawn transset-df --dec -i WID -m 0.2 0.05


# focus
#hc keybind $Mod-BackSpace   cycle_monitor
#hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
#hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent
